version: '3.8'
services:
  mongo:
    image: mongo:latest
    ports:
      - '27018:27017'

  api-server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    volumes:
      - /mern-stack/server/node_modules
      - ./server:/mern-stack/server
    environment:
      - MONGO_URI=mongodb://mongo/merndb
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    depends_on:
      - mongo

  nginx-proxy:
    restart: always
    build:
      context: ./
      dockerfile: ./nginx-proxy/Dockerfile
    ports:
      - '${NGINX_PROXY_PORT}:${NGINX_PROXY_PORT}'
    environment:
      - PLACEHOLDER_1=${PORT}
      - PLACEHOLDER_2=${SERVER_PORT}
      - PLACEHOLDER_3=${NGINX_PROXY_PORT}
      - TZ
    depends_on:
      - api-server
